version: '3.4'

services:

  dart:
    build:
      dockerfile: dart/Dockerfile
      context: .
    tty: true
    working_dir: /workspace
    volumes:
      - .:/workspace

  golang:
    build:
      dockerfile: golang/Dockerfile
      context: .
    tty: true
    working_dir: /workspace
    volumes:
      - .:/workspace

  php:
    build:
      dockerfile: php/Dockerfile
      context: .
      target: workspace
    tty: true
    working_dir: /workspace
    volumes:
      - .:/workspace
