name: eyamluate
description: A starting point of a Dart library.
version: 0.0.1
repository: https://github.com/Jumpaku/eyamluate

environment:
  sdk: ^3.2.5

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
