name: eyamluate
description: A starting point of a Dart library.
version: 0.0.2
repository: https://github.com/Jumpaku/eyamluate

environment:
  sdk: ^3.2.5

# Add regular dependencies here.
dependencies:
  characters: ^1.3.0
  collection: ^1.18.0
  embed_annotation: ^1.2.1
  fixnum: ^1.1.0
  json_schema: ^5.2.0
  path: ^1.9.0
  protobuf: ^3.1.0
  yaml: ^3.1.2
  yaml_edit: ^2.2.1

  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.9
  embed: ^1.3.1
  lints: ^4.0.0
  test: ^1.25.7
