"$schema": "http://json-schema.org/draft-07/schema#"

"$ref": "#/definitions/Eval"

definitions:

  Eval:
    type: object
    properties:
      where:
        type: array
        items:
          "$ref": "#/definitions/FunDef"
      eval:
        "$ref": "#/definitions/Expr"
    required: [eval]
    additionalProperties: false

  FunDef:
    type: object
    properties:
      def:
        type: string
      value:
        "$ref": "#/definitions/Expr"
      with:
        type: array
        items:
          type: string
    required: [def, value]
    additionalProperties: false

  Expr:
    anyOf:
      - "$ref": "#/definitions/Eval"
      - "$ref": "#/definitions/Scalar"
      - "$ref": "#/definitions/NewObj"
      - "$ref": "#/definitions/NewArr"
      - "$ref": "#/definitions/ValJson"
      - "$ref": "#/definitions/RangeIter"
      - "$ref": "#/definitions/ElemAccess"
      - "$ref": "#/definitions/FunCall"
      - "$ref": "#/definitions/CaseBranches"
      - "$ref": "#/definitions/OpUnary"
      - "$ref": "#/definitions/OpBinary"
      - "$ref": "#/definitions/OpVariadic"

  Scalar:
    oneOf:
      - type: number
      - type: boolean
      - type: string

  NewObj:
    type: object
    properties:
      obj:
        type: object
        additionalProperties:
          "$ref": "#/definitions/Expr"
    required: [obj]
    additionalProperties: false

  NewArr:
    type: object
    properties:
      arr:
        type: array
        items:
          "$ref": "#/definitions/Expr"
    required: [ arr ]
    additionalProperties: false

  ValJson:
    type: object
    properties:
      json:
        oneOf:
          - type: number
          - type: boolean
          - type: string
          - type: object
            additionalProperties:
              "$ref": "#/definitions/ValJson/definitions/NonNull"
          - type: array
            items:
              "$ref": "#/definitions/ValJson/definitions/NonNull"
    required: [ json ]
    additionalProperties: false
    definitions:
      NonNull:
        anyOf:
          - type: number
          - type: boolean
          - type: string
          - type: object
            additionalProperties:
              "$ref": "#/definitions/ValJson/definitions/NonNull"
          - type: array
            items:
              "$ref": "#/definitions/ValJson/definitions/NonNull"

  RangeIter:
    type: object
    properties:
      for:
        type: array
        items:
          type: string
        minItems: 2
        maxItems: 2
      in:
        "$ref": "#/definitions/Expr"
      do:
        "$ref": "#/definitions/Expr"
      if:
        "$ref": "#/definitions/Expr"
    required: [ for, in, do ]
    additionalProperties: false

  ElemAccess:
    type: object
    properties:
      get:
        "$ref": "#/definitions/Expr"
      from:
        "$ref": "#/definitions/Expr"
    required: [ get, from ]
    additionalProperties: false

  FunCall:
    type: object
    properties:
      ref:
        type: string
      with:
        type: object
        additionalProperties:
          "$ref": "#/definitions/Expr"
    required: [ ref ]
    additionalProperties: false

  CaseBranches:
    type: object
    properties:
      cases:
        type: array
        items:
          oneOf:
            - "$ref": "#/definitions/CaseWhenThen"
            - "$ref": "#/definitions/CaseOtherwise"
        contains:
          "$ref": "#/definitions/CaseOtherwise"
    required: [ cases ]
    additionalProperties: false

  CaseWhenThen:
    type: object
    properties:
      when:
        "$ref": "#/definitions/Expr"
      then:
        "$ref": "#/definitions/Expr"
    required: [ when, then ]
    additionalProperties: false

  CaseOtherwise:
    type: object
    properties:
      otherwise:
        "$ref": "#/definitions/Expr"
    required: [ otherwise ]
    additionalProperties: false

  OpUnary:
    type: object
    minProperties: 1
    maxProperties: 1
    additionalProperties: false
    properties:
      len:
        "$ref": "#/definitions/Expr"
      not:
        "$ref": "#/definitions/Expr"
      head:
        "$ref": "#/definitions/Expr"
      tail:
        "$ref": "#/definitions/Expr"
      last:
        "$ref": "#/definitions/Expr"
      init:
        "$ref": "#/definitions/Expr"
      flat:
        "$ref": "#/definitions/Expr"
      keys:
        "$ref": "#/definitions/Expr"
      abort:
        "$ref": "#/definitions/Expr"

  OpBinary:
    definitions:
      OpBinaryOperand:
        type: array
        items:
          "$ref": "#/definitions/Expr"
        minItems: 2
        maxItems: 2
    type: object
    minProperties: 1
    maxProperties: 1
    additionalProperties: false
    properties:
      sub:
        "$ref": "#/definitions/OpBinary/definitions/OpBinaryOperand"
      div:
        "$ref": "#/definitions/OpBinary/definitions/OpBinaryOperand"
      mod:
        "$ref": "#/definitions/OpBinary/definitions/OpBinaryOperand"
      eq:
        "$ref": "#/definitions/OpBinary/definitions/OpBinaryOperand"
      neq:
        "$ref": "#/definitions/OpBinary/definitions/OpBinaryOperand"
      lt:
        "$ref": "#/definitions/OpBinary/definitions/OpBinaryOperand"
      lte:
        "$ref": "#/definitions/OpBinary/definitions/OpBinaryOperand"
      gt:
        "$ref": "#/definitions/OpBinary/definitions/OpBinaryOperand"
      gte:
        "$ref": "#/definitions/OpBinary/definitions/OpBinaryOperand"
      cmp:
        "$ref": "#/definitions/OpBinary/definitions/OpBinaryOperand"

  OpVariadic:
    type: object
    minProperties: 1
    maxProperties: 1
    additionalProperties: false
    properties:
      add:
        type: array
        items:
          "$ref": "#/definitions/Expr"
      mul:
        type: array
        items:
          "$ref": "#/definitions/Expr"
      and:
        type: array
        items:
          "$ref": "#/definitions/Expr"
      or:
        type: array
        items:
          "$ref": "#/definitions/Expr"
      cat:
        type: array
        items:
          "$ref": "#/definitions/Expr"
      min:
        type: array
        items:
          "$ref": "#/definitions/Expr"
      max:
        type: array
        items:
          "$ref": "#/definitions/Expr"
      merge:
        type: array
        items:
          "$ref": "#/definitions/Expr"
