// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: ast/validator.proto

package ast

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateOutput_Status int32

const (
	ValidateOutput_OK               ValidateOutput_Status = 0
	ValidateOutput_SCHEMA_ERROR     ValidateOutput_Status = 1
	ValidateOutput_VALIDATION_ERROR ValidateOutput_Status = 2
)

// Enum value maps for ValidateOutput_Status.
var (
	ValidateOutput_Status_name = map[int32]string{
		0: "OK",
		1: "SCHEMA_ERROR",
		2: "VALIDATION_ERROR",
	}
	ValidateOutput_Status_value = map[string]int32{
		"OK":               0,
		"SCHEMA_ERROR":     1,
		"VALIDATION_ERROR": 2,
	}
)

func (x ValidateOutput_Status) Enum() *ValidateOutput_Status {
	p := new(ValidateOutput_Status)
	*p = x
	return p
}

func (x ValidateOutput_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValidateOutput_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_ast_validator_proto_enumTypes[0].Descriptor()
}

func (ValidateOutput_Status) Type() protoreflect.EnumType {
	return &file_ast_validator_proto_enumTypes[0]
}

func (x ValidateOutput_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValidateOutput_Status.Descriptor instead.
func (ValidateOutput_Status) EnumDescriptor() ([]byte, []int) {
	return file_ast_validator_proto_rawDescGZIP(), []int{1, 0}
}

type ValidateInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source string `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
}

func (x *ValidateInput) Reset() {
	*x = ValidateInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ast_validator_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateInput) ProtoMessage() {}

func (x *ValidateInput) ProtoReflect() protoreflect.Message {
	mi := &file_ast_validator_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateInput.ProtoReflect.Descriptor instead.
func (*ValidateInput) Descriptor() ([]byte, []int) {
	return file_ast_validator_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateInput) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type ValidateOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status       ValidateOutput_Status `protobuf:"varint,1,opt,name=status,proto3,enum=ast.ValidateOutput_Status" json:"status,omitempty"`
	ErrorMessage string                `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
}

func (x *ValidateOutput) Reset() {
	*x = ValidateOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ast_validator_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateOutput) ProtoMessage() {}

func (x *ValidateOutput) ProtoReflect() protoreflect.Message {
	mi := &file_ast_validator_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateOutput.ProtoReflect.Descriptor instead.
func (*ValidateOutput) Descriptor() ([]byte, []int) {
	return file_ast_validator_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateOutput) GetStatus() ValidateOutput_Status {
	if x != nil {
		return x.Status
	}
	return ValidateOutput_OK
}

func (x *ValidateOutput) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_ast_validator_proto protoreflect.FileDescriptor

var file_ast_validator_proto_rawDesc = []byte{
	0x0a, 0x13, 0x61, 0x73, 0x74, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x73, 0x74, 0x22, 0x27, 0x0a, 0x0d, 0x56, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x22, 0xa3, 0x01, 0x0a, 0x0e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65,
	0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x32, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x61, 0x73, 0x74, 0x2e, 0x56, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x2e, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x38, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10,
	0x00, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x43, 0x48, 0x45, 0x4d, 0x41, 0x5f, 0x45, 0x52, 0x52, 0x4f,
	0x52, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x41, 0x54, 0x49, 0x4f,
	0x4e, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x02, 0x32, 0x42, 0x0a, 0x09, 0x56, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x35, 0x0a, 0x08, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x12, 0x12, 0x2e, 0x61, 0x73, 0x74, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x13, 0x2e, 0x61, 0x73, 0x74, 0x2e, 0x56, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x00, 0x42, 0x28, 0x5a,
	0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4a, 0x75, 0x6d, 0x70,
	0x61, 0x6b, 0x75, 0x2f, 0x65, 0x79, 0x61, 0x6d, 0x6c, 0x61, 0x74, 0x65, 0x2f, 0x67, 0x6f, 0x6c,
	0x61, 0x6e, 0x67, 0x2f, 0x61, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ast_validator_proto_rawDescOnce sync.Once
	file_ast_validator_proto_rawDescData = file_ast_validator_proto_rawDesc
)

func file_ast_validator_proto_rawDescGZIP() []byte {
	file_ast_validator_proto_rawDescOnce.Do(func() {
		file_ast_validator_proto_rawDescData = protoimpl.X.CompressGZIP(file_ast_validator_proto_rawDescData)
	})
	return file_ast_validator_proto_rawDescData
}

var file_ast_validator_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ast_validator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ast_validator_proto_goTypes = []any{
	(ValidateOutput_Status)(0), // 0: ast.ValidateOutput.Status
	(*ValidateInput)(nil),      // 1: ast.ValidateInput
	(*ValidateOutput)(nil),     // 2: ast.ValidateOutput
}
var file_ast_validator_proto_depIdxs = []int32{
	0, // 0: ast.ValidateOutput.status:type_name -> ast.ValidateOutput.Status
	1, // 1: ast.Validator.Validate:input_type -> ast.ValidateInput
	2, // 2: ast.Validator.Validate:output_type -> ast.ValidateOutput
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ast_validator_proto_init() }
func file_ast_validator_proto_init() {
	if File_ast_validator_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ast_validator_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ValidateInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ast_validator_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ValidateOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ast_validator_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ast_validator_proto_goTypes,
		DependencyIndexes: file_ast_validator_proto_depIdxs,
		EnumInfos:         file_ast_validator_proto_enumTypes,
		MessageInfos:      file_ast_validator_proto_msgTypes,
	}.Build()
	File_ast_validator_proto = out.File
	file_ast_validator_proto_rawDesc = nil
	file_ast_validator_proto_goTypes = nil
	file_ast_validator_proto_depIdxs = nil
}
