// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: testing/testing.proto

package yaml

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Testcase struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InputYaml string `protobuf:"bytes,1,opt,name=input_yaml,json=inputYaml,proto3" json:"input_yaml,omitempty"`
	WantError bool   `protobuf:"varint,2,opt,name=want_error,json=wantError,proto3" json:"want_error,omitempty"`
	WantValue *Value `protobuf:"bytes,3,opt,name=want_value,json=wantValue,proto3" json:"want_value,omitempty"`
}

func (x *Testcase) Reset() {
	*x = Testcase{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testing_testing_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Testcase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Testcase) ProtoMessage() {}

func (x *Testcase) ProtoReflect() protoreflect.Message {
	mi := &file_testing_testing_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Testcase.ProtoReflect.Descriptor instead.
func (*Testcase) Descriptor() ([]byte, []int) {
	return file_testing_testing_proto_rawDescGZIP(), []int{0}
}

func (x *Testcase) GetInputYaml() string {
	if x != nil {
		return x.InputYaml
	}
	return ""
}

func (x *Testcase) GetWantError() bool {
	if x != nil {
		return x.WantError
	}
	return false
}

func (x *Testcase) GetWantValue() *Value {
	if x != nil {
		return x.WantValue
	}
	return nil
}

var File_testing_testing_proto protoreflect.FileDescriptor

var file_testing_testing_proto_rawDesc = []byte{
	0x0a, 0x15, 0x74, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x69, 0x6e,
	0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x79, 0x61, 0x6d, 0x6c, 0x1a, 0x10, 0x79,
	0x61, 0x6d, 0x6c, 0x2f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x74, 0x0a, 0x08, 0x54, 0x65, 0x73, 0x74, 0x63, 0x61, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x69,
	0x6e, 0x70, 0x75, 0x74, 0x5f, 0x79, 0x61, 0x6d, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x59, 0x61, 0x6d, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x77, 0x61,
	0x6e, 0x74, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09,
	0x77, 0x61, 0x6e, 0x74, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x2a, 0x0a, 0x0a, 0x77, 0x61, 0x6e,
	0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e,
	0x79, 0x61, 0x6d, 0x6c, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x09, 0x77, 0x61, 0x6e, 0x74,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x4a, 0x75, 0x6d, 0x70, 0x61, 0x6b, 0x75, 0x2f, 0x65, 0x79, 0x61, 0x6d,
	0x6c, 0x61, 0x74, 0x65, 0x2f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2f, 0x79, 0x61, 0x6d, 0x6c,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_testing_testing_proto_rawDescOnce sync.Once
	file_testing_testing_proto_rawDescData = file_testing_testing_proto_rawDesc
)

func file_testing_testing_proto_rawDescGZIP() []byte {
	file_testing_testing_proto_rawDescOnce.Do(func() {
		file_testing_testing_proto_rawDescData = protoimpl.X.CompressGZIP(file_testing_testing_proto_rawDescData)
	})
	return file_testing_testing_proto_rawDescData
}

var file_testing_testing_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_testing_testing_proto_goTypes = []any{
	(*Testcase)(nil), // 0: yaml.Testcase
	(*Value)(nil),    // 1: yaml.Value
}
var file_testing_testing_proto_depIdxs = []int32{
	1, // 0: yaml.Testcase.want_value:type_name -> yaml.Value
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_testing_testing_proto_init() }
func file_testing_testing_proto_init() {
	if File_testing_testing_proto != nil {
		return
	}
	file_yaml_value_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_testing_testing_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Testcase); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_testing_testing_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_testing_testing_proto_goTypes,
		DependencyIndexes: file_testing_testing_proto_depIdxs,
		MessageInfos:      file_testing_testing_proto_msgTypes,
	}.Build()
	File_testing_testing_proto = out.File
	file_testing_testing_proto_rawDesc = nil
	file_testing_testing_proto_goTypes = nil
	file_testing_testing_proto_depIdxs = nil
}
