// @generated by protoc-gen-es v2.0.0 with parameter "target=ts,import_extension=js"
// @generated from file yaml/decoder.proto (package yaml, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Value } from "./value_pb.js";
import { file_yaml_value } from "./value_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file yaml/decoder.proto.
 */
export const file_yaml_decoder: GenFile = /*@__PURE__*/
  fileDesc("ChJ5YW1sL2RlY29kZXIucHJvdG8SBHlhbWwiGwoLRGVjb2RlSW5wdXQSDAoEeWFtbBgBIAEoCSJTCgxEZWNvZGVPdXRwdXQSEAoIaXNfZXJyb3IYASABKAgSFQoNZXJyb3JfbWVzc2FnZRgCIAEoCRIaCgV2YWx1ZRgDIAEoCzILLnlhbWwuVmFsdWUyPAoHRGVjb2RlchIxCgZEZWNvZGUSES55YW1sLkRlY29kZUlucHV0GhIueWFtbC5EZWNvZGVPdXRwdXQiAEJ2Cghjb20ueWFtbEIMRGVjb2RlclByb3RvUAFaJ2dpdGh1Yi5jb20vSnVtcGFrdS9leWFtbGF0ZS9nb2xhbmcveWFtbKICA1lYWKoCBFlhbWzCAgJQQsoCBFlhbWziAhBZYW1sXEdQQk1ldGFkYXRh6gIEWWFtbGIGcHJvdG8z", [file_yaml_value]);

/**
 * @generated from message yaml.DecodeInput
 */
export type DecodeInput = Message<"yaml.DecodeInput"> & {
  /**
   * @generated from field: string yaml = 1;
   */
  yaml: string;
};

/**
 * Describes the message yaml.DecodeInput.
 * Use `create(DecodeInputSchema)` to create a new message.
 */
export const DecodeInputSchema: GenMessage<DecodeInput> = /*@__PURE__*/
  messageDesc(file_yaml_decoder, 0);

/**
 * @generated from message yaml.DecodeOutput
 */
export type DecodeOutput = Message<"yaml.DecodeOutput"> & {
  /**
   * @generated from field: bool is_error = 1;
   */
  isError: boolean;

  /**
   * @generated from field: string error_message = 2;
   */
  errorMessage: string;

  /**
   * @generated from field: yaml.Value value = 3;
   */
  value?: Value;
};

/**
 * Describes the message yaml.DecodeOutput.
 * Use `create(DecodeOutputSchema)` to create a new message.
 */
export const DecodeOutputSchema: GenMessage<DecodeOutput> = /*@__PURE__*/
  messageDesc(file_yaml_decoder, 1);

/**
 * @generated from service yaml.Decoder
 */
export const Decoder: GenService<{
  /**
   * @generated from rpc yaml.Decoder.Decode
   */
  decode: {
    methodKind: "unary";
    input: typeof DecodeInputSchema;
    output: typeof DecodeOutputSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_yaml_decoder, 0);

