// @generated by protoc-gen-es v2.0.0 with parameter "target=ts,import_extension=js"
// @generated from file yaml/encoder.proto (package yaml, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Value } from "./value_pb.js";
import { file_yaml_value } from "./value_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file yaml/encoder.proto.
 */
export const file_yaml_encoder: GenFile = /*@__PURE__*/
  fileDesc("ChJ5YW1sL2VuY29kZXIucHJvdG8SBHlhbWwiXQoLRW5jb2RlSW5wdXQSIgoGZm9ybWF0GAEgASgOMhIueWFtbC5FbmNvZGVGb3JtYXQSDgoGcHJldHR5GAIgASgIEhoKBXZhbHVlGAMgASgLMgsueWFtbC5WYWx1ZSJHCgxFbmNvZGVPdXRwdXQSEAoIaXNfZXJyb3IYASABKAgSFQoNZXJyb3JfbWVzc2FnZRgCIAEoCRIOCgZyZXN1bHQYAyABKAkqPgoMRW5jb2RlRm9ybWF0EhYKEkVOQ09ERV9GT1JNQVRfWUFNTBAAEhYKEkVOQ09ERV9GT1JNQVRfSlNPThABMjwKB0VuY29kZXISMQoGRW5jb2RlEhEueWFtbC5FbmNvZGVJbnB1dBoSLnlhbWwuRW5jb2RlT3V0cHV0IgBCdgoIY29tLnlhbWxCDEVuY29kZXJQcm90b1ABWidnaXRodWIuY29tL0p1bXBha3UvZXlhbWxhdGUvZ29sYW5nL3lhbWyiAgNZWFiqAgRZYW1swgICUELKAgRZYW1s4gIQWWFtbFxHUEJNZXRhZGF0YeoCBFlhbWxiBnByb3RvMw", [file_yaml_value]);

/**
 * @generated from message yaml.EncodeInput
 */
export type EncodeInput = Message<"yaml.EncodeInput"> & {
  /**
   * @generated from field: yaml.EncodeFormat format = 1;
   */
  format: EncodeFormat;

  /**
   * @generated from field: bool pretty = 2;
   */
  pretty: boolean;

  /**
   * @generated from field: yaml.Value value = 3;
   */
  value?: Value;
};

/**
 * Describes the message yaml.EncodeInput.
 * Use `create(EncodeInputSchema)` to create a new message.
 */
export const EncodeInputSchema: GenMessage<EncodeInput> = /*@__PURE__*/
  messageDesc(file_yaml_encoder, 0);

/**
 * @generated from message yaml.EncodeOutput
 */
export type EncodeOutput = Message<"yaml.EncodeOutput"> & {
  /**
   * @generated from field: bool is_error = 1;
   */
  isError: boolean;

  /**
   * @generated from field: string error_message = 2;
   */
  errorMessage: string;

  /**
   * @generated from field: string result = 3;
   */
  result: string;
};

/**
 * Describes the message yaml.EncodeOutput.
 * Use `create(EncodeOutputSchema)` to create a new message.
 */
export const EncodeOutputSchema: GenMessage<EncodeOutput> = /*@__PURE__*/
  messageDesc(file_yaml_encoder, 1);

/**
 * @generated from enum yaml.EncodeFormat
 */
export enum EncodeFormat {
  /**
   * @generated from enum value: ENCODE_FORMAT_YAML = 0;
   */
  YAML = 0,

  /**
   * @generated from enum value: ENCODE_FORMAT_JSON = 1;
   */
  JSON = 1,
}

/**
 * Describes the enum yaml.EncodeFormat.
 */
export const EncodeFormatSchema: GenEnum<EncodeFormat> = /*@__PURE__*/
  enumDesc(file_yaml_encoder, 0);

/**
 * @generated from service yaml.Encoder
 */
export const Encoder: GenService<{
  /**
   * @generated from rpc yaml.Encoder.Encode
   */
  encode: {
    methodKind: "unary";
    input: typeof EncodeInputSchema;
    output: typeof EncodeOutputSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_yaml_encoder, 0);

