// @generated by protoc-gen-es v2.0.0 with parameter "target=ts,import_extension=js"
// @generated from file yaml/value.proto (package yaml, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file yaml/value.proto.
 */
export const file_yaml_value: GenFile = /*@__PURE__*/
  fileDesc("ChB5YW1sL3ZhbHVlLnByb3RvEgR5YW1sIr8BCgVWYWx1ZRIYCgR0eXBlGAEgASgOMgoueWFtbC5UeXBlEgwKBGJvb2wYAiABKAgSCwoDbnVtGAMgASgBEgsKA3N0chgEIAEoCRIYCgNhcnIYBSADKAsyCy55YW1sLlZhbHVlEiEKA29iahgGIAMoCzIULnlhbWwuVmFsdWUuT2JqRW50cnkaNwoIT2JqRW50cnkSCwoDa2V5GAEgASgJEhoKBXZhbHVlGAIgASgLMgsueWFtbC5WYWx1ZToCOAEqcgoEVHlwZRIUChBUWVBFX1VOU1BFQ0lGSUVEEAASDQoJVFlQRV9OVUxMEAESDQoJVFlQRV9CT09MEAISDAoIVFlQRV9OVU0QAxIMCghUWVBFX1NUUhAEEgwKCFRZUEVfQVJSEAUSDAoIVFlQRV9PQkoQBkJ0Cghjb20ueWFtbEIKVmFsdWVQcm90b1ABWidnaXRodWIuY29tL0p1bXBha3UvZXlhbWxhdGUvZ29sYW5nL3lhbWyiAgNZWFiqAgRZYW1swgICUELKAgRZYW1s4gIQWWFtbFxHUEJNZXRhZGF0YeoCBFlhbWxiBnByb3RvMw");

/**
 * @generated from message yaml.Value
 */
export type Value = Message<"yaml.Value"> & {
  /**
   * @generated from field: yaml.Type type = 1;
   */
  type: Type;

  /**
   * @generated from field: bool bool = 2;
   */
  bool: boolean;

  /**
   * @generated from field: double num = 3;
   */
  num: number;

  /**
   * @generated from field: string str = 4;
   */
  str: string;

  /**
   * @generated from field: repeated yaml.Value arr = 5;
   */
  arr: Value[];

  /**
   * @generated from field: map<string, yaml.Value> obj = 6;
   */
  obj: { [key: string]: Value };
};

/**
 * Describes the message yaml.Value.
 * Use `create(ValueSchema)` to create a new message.
 */
export const ValueSchema: GenMessage<Value> = /*@__PURE__*/
  messageDesc(file_yaml_value, 0);

/**
 * @generated from enum yaml.Type
 */
export enum Type {
  /**
   * @generated from enum value: TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: TYPE_NULL = 1;
   */
  NULL = 1,

  /**
   * @generated from enum value: TYPE_BOOL = 2;
   */
  BOOL = 2,

  /**
   * @generated from enum value: TYPE_NUM = 3;
   */
  NUM = 3,

  /**
   * @generated from enum value: TYPE_STR = 4;
   */
  STR = 4,

  /**
   * @generated from enum value: TYPE_ARR = 5;
   */
  ARR = 5,

  /**
   * @generated from enum value: TYPE_OBJ = 6;
   */
  OBJ = 6,
}

/**
 * Describes the enum yaml.Type.
 */
export const TypeSchema: GenEnum<Type> = /*@__PURE__*/
  enumDesc(file_yaml_value, 0);

