// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: yaml/encoder.proto

package yaml

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EncodeFormat int32

const (
	EncodeFormat_ENCODE_FORMAT_YAML EncodeFormat = 0
	EncodeFormat_ENCODE_FORMAT_JSON EncodeFormat = 1
)

// Enum value maps for EncodeFormat.
var (
	EncodeFormat_name = map[int32]string{
		0: "ENCODE_FORMAT_YAML",
		1: "ENCODE_FORMAT_JSON",
	}
	EncodeFormat_value = map[string]int32{
		"ENCODE_FORMAT_YAML": 0,
		"ENCODE_FORMAT_JSON": 1,
	}
)

func (x EncodeFormat) Enum() *EncodeFormat {
	p := new(EncodeFormat)
	*p = x
	return p
}

func (x EncodeFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EncodeFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_yaml_encoder_proto_enumTypes[0].Descriptor()
}

func (EncodeFormat) Type() protoreflect.EnumType {
	return &file_yaml_encoder_proto_enumTypes[0]
}

func (x EncodeFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EncodeFormat.Descriptor instead.
func (EncodeFormat) EnumDescriptor() ([]byte, []int) {
	return file_yaml_encoder_proto_rawDescGZIP(), []int{0}
}

type EncodeInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Format EncodeFormat `protobuf:"varint,1,opt,name=format,proto3,enum=yaml.EncodeFormat" json:"format,omitempty"`
	Pretty bool         `protobuf:"varint,2,opt,name=pretty,proto3" json:"pretty,omitempty"`
	Value  *Value       `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *EncodeInput) Reset() {
	*x = EncodeInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yaml_encoder_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EncodeInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncodeInput) ProtoMessage() {}

func (x *EncodeInput) ProtoReflect() protoreflect.Message {
	mi := &file_yaml_encoder_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncodeInput.ProtoReflect.Descriptor instead.
func (*EncodeInput) Descriptor() ([]byte, []int) {
	return file_yaml_encoder_proto_rawDescGZIP(), []int{0}
}

func (x *EncodeInput) GetFormat() EncodeFormat {
	if x != nil {
		return x.Format
	}
	return EncodeFormat_ENCODE_FORMAT_YAML
}

func (x *EncodeInput) GetPretty() bool {
	if x != nil {
		return x.Pretty
	}
	return false
}

func (x *EncodeInput) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type EncodeOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsError      bool   `protobuf:"varint,1,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Result       string `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *EncodeOutput) Reset() {
	*x = EncodeOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yaml_encoder_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EncodeOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncodeOutput) ProtoMessage() {}

func (x *EncodeOutput) ProtoReflect() protoreflect.Message {
	mi := &file_yaml_encoder_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncodeOutput.ProtoReflect.Descriptor instead.
func (*EncodeOutput) Descriptor() ([]byte, []int) {
	return file_yaml_encoder_proto_rawDescGZIP(), []int{1}
}

func (x *EncodeOutput) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

func (x *EncodeOutput) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *EncodeOutput) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_yaml_encoder_proto protoreflect.FileDescriptor

var file_yaml_encoder_proto_rawDesc = []byte{
	0x0a, 0x12, 0x79, 0x61, 0x6d, 0x6c, 0x2f, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x79, 0x61, 0x6d, 0x6c, 0x1a, 0x10, 0x79, 0x61, 0x6d, 0x6c,
	0x2f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x74, 0x0a, 0x0b,
	0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x2a, 0x0a, 0x06, 0x66,
	0x6f, 0x72, 0x6d, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x79, 0x61,
	0x6d, 0x6c, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x52,
	0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x65, 0x74, 0x74,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x70, 0x72, 0x65, 0x74, 0x74, 0x79, 0x12,
	0x21, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x79, 0x61, 0x6d, 0x6c, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0x66, 0x0a, 0x0c, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x4f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x73, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x23, 0x0a,
	0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2a, 0x3e, 0x0a, 0x0c, 0x45, 0x6e,
	0x63, 0x6f, 0x64, 0x65, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x16, 0x0a, 0x12, 0x45, 0x4e,
	0x43, 0x4f, 0x44, 0x45, 0x5f, 0x46, 0x4f, 0x52, 0x4d, 0x41, 0x54, 0x5f, 0x59, 0x41, 0x4d, 0x4c,
	0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x45, 0x4e, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x46, 0x4f, 0x52,
	0x4d, 0x41, 0x54, 0x5f, 0x4a, 0x53, 0x4f, 0x4e, 0x10, 0x01, 0x32, 0x3c, 0x0a, 0x07, 0x45, 0x6e,
	0x63, 0x6f, 0x64, 0x65, 0x72, 0x12, 0x31, 0x0a, 0x06, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x12,
	0x11, 0x2e, 0x79, 0x61, 0x6d, 0x6c, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x70,
	0x75, 0x74, 0x1a, 0x12, 0x2e, 0x79, 0x61, 0x6d, 0x6c, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65,
	0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x00, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4a, 0x75, 0x6d, 0x70, 0x61, 0x6b, 0x75, 0x2f, 0x65,
	0x79, 0x61, 0x6d, 0x6c, 0x61, 0x74, 0x65, 0x2f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2f, 0x79,
	0x61, 0x6d, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_yaml_encoder_proto_rawDescOnce sync.Once
	file_yaml_encoder_proto_rawDescData = file_yaml_encoder_proto_rawDesc
)

func file_yaml_encoder_proto_rawDescGZIP() []byte {
	file_yaml_encoder_proto_rawDescOnce.Do(func() {
		file_yaml_encoder_proto_rawDescData = protoimpl.X.CompressGZIP(file_yaml_encoder_proto_rawDescData)
	})
	return file_yaml_encoder_proto_rawDescData
}

var file_yaml_encoder_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_yaml_encoder_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_yaml_encoder_proto_goTypes = []any{
	(EncodeFormat)(0),    // 0: yaml.EncodeFormat
	(*EncodeInput)(nil),  // 1: yaml.EncodeInput
	(*EncodeOutput)(nil), // 2: yaml.EncodeOutput
	(*Value)(nil),        // 3: yaml.Value
}
var file_yaml_encoder_proto_depIdxs = []int32{
	0, // 0: yaml.EncodeInput.format:type_name -> yaml.EncodeFormat
	3, // 1: yaml.EncodeInput.value:type_name -> yaml.Value
	1, // 2: yaml.Encoder.Encode:input_type -> yaml.EncodeInput
	2, // 3: yaml.Encoder.Encode:output_type -> yaml.EncodeOutput
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_yaml_encoder_proto_init() }
func file_yaml_encoder_proto_init() {
	if File_yaml_encoder_proto != nil {
		return
	}
	file_yaml_value_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_yaml_encoder_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*EncodeInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yaml_encoder_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*EncodeOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_yaml_encoder_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_yaml_encoder_proto_goTypes,
		DependencyIndexes: file_yaml_encoder_proto_depIdxs,
		EnumInfos:         file_yaml_encoder_proto_enumTypes,
		MessageInfos:      file_yaml_encoder_proto_msgTypes,
	}.Build()
	File_yaml_encoder_proto = out.File
	file_yaml_encoder_proto_rawDesc = nil
	file_yaml_encoder_proto_goTypes = nil
	file_yaml_encoder_proto_depIdxs = nil
}
