// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: yaml/unmarshaller.proto

package yaml

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UnmarshalInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Yaml string `protobuf:"bytes,1,opt,name=yaml,proto3" json:"yaml,omitempty"`
}

func (x *UnmarshalInput) Reset() {
	*x = UnmarshalInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yaml_unmarshaller_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnmarshalInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmarshalInput) ProtoMessage() {}

func (x *UnmarshalInput) ProtoReflect() protoreflect.Message {
	mi := &file_yaml_unmarshaller_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmarshalInput.ProtoReflect.Descriptor instead.
func (*UnmarshalInput) Descriptor() ([]byte, []int) {
	return file_yaml_unmarshaller_proto_rawDescGZIP(), []int{0}
}

func (x *UnmarshalInput) GetYaml() string {
	if x != nil {
		return x.Yaml
	}
	return ""
}

type UnmarshalOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value *Value `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *UnmarshalOutput) Reset() {
	*x = UnmarshalOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yaml_unmarshaller_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnmarshalOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmarshalOutput) ProtoMessage() {}

func (x *UnmarshalOutput) ProtoReflect() protoreflect.Message {
	mi := &file_yaml_unmarshaller_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmarshalOutput.ProtoReflect.Descriptor instead.
func (*UnmarshalOutput) Descriptor() ([]byte, []int) {
	return file_yaml_unmarshaller_proto_rawDescGZIP(), []int{1}
}

func (x *UnmarshalOutput) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_yaml_unmarshaller_proto protoreflect.FileDescriptor

var file_yaml_unmarshaller_proto_rawDesc = []byte{
	0x0a, 0x17, 0x79, 0x61, 0x6d, 0x6c, 0x2f, 0x75, 0x6e, 0x6d, 0x61, 0x72, 0x73, 0x68, 0x61, 0x6c,
	0x6c, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x79, 0x61, 0x6d, 0x6c, 0x1a,
	0x10, 0x79, 0x61, 0x6d, 0x6c, 0x2f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x24, 0x0a, 0x0e, 0x55, 0x6e, 0x6d, 0x61, 0x72, 0x73, 0x68, 0x61, 0x6c, 0x49, 0x6e,
	0x70, 0x75, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x79, 0x61, 0x6d, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x79, 0x61, 0x6d, 0x6c, 0x22, 0x34, 0x0a, 0x0f, 0x55, 0x6e, 0x6d, 0x61, 0x72,
	0x73, 0x68, 0x61, 0x6c, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x21, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x79, 0x61, 0x6d, 0x6c,
	0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0x4a, 0x0a,
	0x0c, 0x55, 0x6e, 0x6d, 0x61, 0x72, 0x73, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x12, 0x3a, 0x0a,
	0x09, 0x55, 0x6e, 0x6d, 0x61, 0x72, 0x73, 0x68, 0x61, 0x6c, 0x12, 0x14, 0x2e, 0x79, 0x61, 0x6d,
	0x6c, 0x2e, 0x55, 0x6e, 0x6d, 0x61, 0x72, 0x73, 0x68, 0x61, 0x6c, 0x49, 0x6e, 0x70, 0x75, 0x74,
	0x1a, 0x15, 0x2e, 0x79, 0x61, 0x6d, 0x6c, 0x2e, 0x55, 0x6e, 0x6d, 0x61, 0x72, 0x73, 0x68, 0x61,
	0x6c, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x00, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4a, 0x75, 0x6d, 0x70, 0x61, 0x6b, 0x75, 0x2f,
	0x65, 0x79, 0x61, 0x6d, 0x6c, 0x61, 0x74, 0x65, 0x2f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2f,
	0x70, 0x62, 0x2f, 0x79, 0x61, 0x6d, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_yaml_unmarshaller_proto_rawDescOnce sync.Once
	file_yaml_unmarshaller_proto_rawDescData = file_yaml_unmarshaller_proto_rawDesc
)

func file_yaml_unmarshaller_proto_rawDescGZIP() []byte {
	file_yaml_unmarshaller_proto_rawDescOnce.Do(func() {
		file_yaml_unmarshaller_proto_rawDescData = protoimpl.X.CompressGZIP(file_yaml_unmarshaller_proto_rawDescData)
	})
	return file_yaml_unmarshaller_proto_rawDescData
}

var file_yaml_unmarshaller_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_yaml_unmarshaller_proto_goTypes = []any{
	(*UnmarshalInput)(nil),  // 0: yaml.UnmarshalInput
	(*UnmarshalOutput)(nil), // 1: yaml.UnmarshalOutput
	(*Value)(nil),           // 2: yaml.Value
}
var file_yaml_unmarshaller_proto_depIdxs = []int32{
	2, // 0: yaml.UnmarshalOutput.value:type_name -> yaml.Value
	0, // 1: yaml.Unmarshaller.Unmarshal:input_type -> yaml.UnmarshalInput
	1, // 2: yaml.Unmarshaller.Unmarshal:output_type -> yaml.UnmarshalOutput
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_yaml_unmarshaller_proto_init() }
func file_yaml_unmarshaller_proto_init() {
	if File_yaml_unmarshaller_proto != nil {
		return
	}
	file_yaml_value_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_yaml_unmarshaller_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*UnmarshalInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yaml_unmarshaller_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*UnmarshalOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_yaml_unmarshaller_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_yaml_unmarshaller_proto_goTypes,
		DependencyIndexes: file_yaml_unmarshaller_proto_depIdxs,
		MessageInfos:      file_yaml_unmarshaller_proto_msgTypes,
	}.Build()
	File_yaml_unmarshaller_proto = out.File
	file_yaml_unmarshaller_proto_rawDesc = nil
	file_yaml_unmarshaller_proto_goTypes = nil
	file_yaml_unmarshaller_proto_depIdxs = nil
}
