// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: yaml/value.proto

package yaml

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Type int32

const (
	Type_UNSPECIFIED Type = 0
	Type_NULL        Type = 1
	Type_BOOL        Type = 2
	Type_NUM         Type = 3
	Type_STR         Type = 4
	Type_ARR         Type = 5
	Type_OBJ         Type = 6
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "NULL",
		2: "BOOL",
		3: "NUM",
		4: "STR",
		5: "ARR",
		6: "OBJ",
	}
	Type_value = map[string]int32{
		"UNSPECIFIED": 0,
		"NULL":        1,
		"BOOL":        2,
		"NUM":         3,
		"STR":         4,
		"ARR":         5,
		"OBJ":         6,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_yaml_value_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_yaml_value_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_yaml_value_proto_rawDescGZIP(), []int{0}
}

type Value struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type Type              `protobuf:"varint,1,opt,name=type,proto3,enum=yaml.Type" json:"type,omitempty"`
	Bool bool              `protobuf:"varint,2,opt,name=bool,proto3" json:"bool,omitempty"`
	Num  float64           `protobuf:"fixed64,3,opt,name=num,proto3" json:"num,omitempty"`
	Str  string            `protobuf:"bytes,4,opt,name=str,proto3" json:"str,omitempty"`
	Arr  []*Value          `protobuf:"bytes,5,rep,name=arr,proto3" json:"arr,omitempty"`
	Obj  map[string]*Value `protobuf:"bytes,6,rep,name=obj,proto3" json:"obj,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Value) Reset() {
	*x = Value{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yaml_value_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_yaml_value_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_yaml_value_proto_rawDescGZIP(), []int{0}
}

func (x *Value) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_UNSPECIFIED
}

func (x *Value) GetBool() bool {
	if x != nil {
		return x.Bool
	}
	return false
}

func (x *Value) GetNum() float64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *Value) GetStr() string {
	if x != nil {
		return x.Str
	}
	return ""
}

func (x *Value) GetArr() []*Value {
	if x != nil {
		return x.Arr
	}
	return nil
}

func (x *Value) GetObj() map[string]*Value {
	if x != nil {
		return x.Obj
	}
	return nil
}

var File_yaml_value_proto protoreflect.FileDescriptor

var file_yaml_value_proto_rawDesc = []byte{
	0x0a, 0x10, 0x79, 0x61, 0x6d, 0x6c, 0x2f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x79, 0x61, 0x6d, 0x6c, 0x22, 0xeb, 0x01, 0x0a, 0x05, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x1e, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0a, 0x2e, 0x79, 0x61, 0x6d, 0x6c, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x6f, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x04, 0x62, 0x6f, 0x6f, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x74, 0x72, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x74, 0x72, 0x12, 0x1d, 0x0a, 0x03, 0x61, 0x72,
	0x72, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x79, 0x61, 0x6d, 0x6c, 0x2e, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x52, 0x03, 0x61, 0x72, 0x72, 0x12, 0x26, 0x0a, 0x03, 0x6f, 0x62, 0x6a,
	0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x79, 0x61, 0x6d, 0x6c, 0x2e, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x2e, 0x4f, 0x62, 0x6a, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x03, 0x6f, 0x62,
	0x6a, 0x1a, 0x43, 0x0a, 0x08, 0x4f, 0x62, 0x6a, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x21, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x79, 0x61, 0x6d, 0x6c, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x2a, 0x4f, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0f,
	0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12,
	0x08, 0x0a, 0x04, 0x4e, 0x55, 0x4c, 0x4c, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x42, 0x4f, 0x4f,
	0x4c, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x4e, 0x55, 0x4d, 0x10, 0x03, 0x12, 0x07, 0x0a, 0x03,
	0x53, 0x54, 0x52, 0x10, 0x04, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x52, 0x52, 0x10, 0x05, 0x12, 0x07,
	0x0a, 0x03, 0x4f, 0x42, 0x4a, 0x10, 0x06, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4a, 0x75, 0x6d, 0x70, 0x61, 0x6b, 0x75, 0x2f, 0x65, 0x79,
	0x61, 0x6d, 0x6c, 0x61, 0x74, 0x65, 0x2f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2f, 0x79, 0x61,
	0x6d, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_yaml_value_proto_rawDescOnce sync.Once
	file_yaml_value_proto_rawDescData = file_yaml_value_proto_rawDesc
)

func file_yaml_value_proto_rawDescGZIP() []byte {
	file_yaml_value_proto_rawDescOnce.Do(func() {
		file_yaml_value_proto_rawDescData = protoimpl.X.CompressGZIP(file_yaml_value_proto_rawDescData)
	})
	return file_yaml_value_proto_rawDescData
}

var file_yaml_value_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_yaml_value_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_yaml_value_proto_goTypes = []any{
	(Type)(0),     // 0: yaml.Type
	(*Value)(nil), // 1: yaml.Value
	nil,           // 2: yaml.Value.ObjEntry
}
var file_yaml_value_proto_depIdxs = []int32{
	0, // 0: yaml.Value.type:type_name -> yaml.Type
	1, // 1: yaml.Value.arr:type_name -> yaml.Value
	2, // 2: yaml.Value.obj:type_name -> yaml.Value.ObjEntry
	1, // 3: yaml.Value.ObjEntry.value:type_name -> yaml.Value
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_yaml_value_proto_init() }
func file_yaml_value_proto_init() {
	if File_yaml_value_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_yaml_value_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Value); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_yaml_value_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_yaml_value_proto_goTypes,
		DependencyIndexes: file_yaml_value_proto_depIdxs,
		EnumInfos:         file_yaml_value_proto_enumTypes,
		MessageInfos:      file_yaml_value_proto_msgTypes,
	}.Build()
	File_yaml_value_proto = out.File
	file_yaml_value_proto_rawDesc = nil
	file_yaml_value_proto_goTypes = nil
	file_yaml_value_proto_depIdxs = nil
}
